server.port: 8080

## define se vai utilizar a solução onde authorization server e resource server estão juntos ou separados
## definir como true, significa que o oauth provider está todo configurado aqui na aplicação bookserver
## definir como false, significa que essa aplicação só possui configuração para o resource server
## -> quando está como false, para validar o token é preciso que o authorization server esteja salvando os dados do
## -> client details em um banco de dados (ao invés de em memória).
oauth:
  enabled: true
  all-in-one: true

## multiplas configurações de datasource do spring
spring:
  ds-bookserver:
    url: jdbc:mysql://localhost/bookserver
    username: bookserver
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  ds-oauth:
    url: jdbc:mysql://localhost/bookserver_oauth
    username: bookserver_oauth
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        hbm2ddl:
          auto: validate

## configuracoes open id
## informações encontradas no document discovery -> https://accounts.google.com/.well-known/openid-configuration
google:
  client_id: 210054471756-e2q5ia46ort3m1k284io57gv5qiuu5kk.apps.googleusercontent.com
  client_secret: UYg71Qcfx1PUrOplwJb3tXiV
  user_authorization_uri: https://accounts.google.com/o/oauth2/v2/auth
  access_token_uri: https://www.googleapis.com/oauth2/v4/token
  redirect_uri: http://localhost:8080/google/callback
  userinfo_endpoint: https://www.googleapis.com/oauth2/v3/userinfo
